[package]
name = "pdc"
version = "0.1.0"
edition = "2021"
authors = ["tropicbliss <tropicbliss@protonmail.com>"]
license = "MIT"

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
crc = "2.1.0"
serde = "1.0.136"
thiserror = "1.0.30"
